#!/bin/sh

set -x

#  1.  Generate CSF expansions
#      1.1 MR for 2s(2), 2p(2), 2s3s, 2s3d; and 2s2p, 2s3p, 2p3s

rcsfggenerate_csfg <<EOF1
0
1s(2,i)2s(2,*)
1s(2,i)2p(2,*)
1s(2,i)2s(1,*)3s(1,*)
1s(2,i)2s(1,*)3d(1,*)

3s,3p,3d
0,6
0
y
1s(2,i)2s(1,*)2p(1,*)
1s(2,i)2s(1,*)3p(1,*)
1s(2,i)2p(1,*)3s(1,*)

3s,3p,3d
0,4
0
n
EOF1

cp rcsfg.out  n3.g
cp rlabel.out n3.l
cp rcsfg.out  rcsfgmr.inp
mv rlabel.out rcsfgmr.l
