!***********************************************************************
!                                                                      *
      SUBROUTINE MATRIXBLOCK34(ICSAV,IRSAV,NCOEC,INCOR,NCTEC,INC2,     &
                 NMCBP,NCORE,ELSTO)
!
!   This subroutine calls onescalar and computes one electron          *
!   matrix elements when IC and IR are of type 3 and 4                 *
!                                                                      *
!   Written by CHONG-YANG CHEN                               JUNE 2020 *
!   Last modification by C. Y. Chen                          Jan  2022 *
!                                                                      *
!***********************************************************************
!...Translated by Gediminas Gaigalas  May 2021
!-----------------------------------------------
!   M o d u l e s
!-----------------------------------------------
      USE vast_kind_param, ONLY: DOUBLE
      USE parameter_def,   ONLY: NNNP
      use symmatrix_mod
      USE buffer_C,   ONLY: NVCOEF, LABEL, COEFF
      USE debug_C,    ONLY: IBUG1
      USE decide_C
      USE def_C
      USE orb_C
!-----------------------------------------------
!   I n t e r f a c e   B l o c k s
!-----------------------------------------------
      IMPLICIT NONE
      EXTERNAL BREID,CORD
!----------------------------------------------
!   D u m m y   A r g u m e n t s
!-----------------------------------------------
      INTEGER :: ICSAV,IRSAV,NCOEC,INCOR,NCTEC,INC2,NMCBP,NCORE
      REAL(DOUBLE)        :: ELSTO
!-----------------------------------------------
!   L o c a l   P a r a m e t e r s
!-----------------------------------------------
!      REAL(DOUBLE), PARAMETER :: CUTOFF = 1.0D-20
!-----------------------------------------------
!   L o c a l   V a r i a b l e s
!-----------------------------------------------
      LOGICAL :: FLAGL,FLAGNONE,FLAGU
      REAL(DOUBLE) :: EMTTMP,ATWINV,ENONSYM,TCOEFF,VCOEFF
      REAL(DOUBLE), DIMENSION(NNNW) :: TSHELL
      INTEGER :: I,IC,IC0,IV,ICPTI,ICPTIJ,ICPTJ,ICW,IFLAG12,IR,IR0
      INTEGER :: IRPTK,IRPTKL,IRPTL,IRW,J,K,L,LABVTMP,M,MTYPE,N,NDIFF
      INTEGER :: NORBCOL,NORBROWL,NORBROWU, IRORBIF(3,3)
      LOGICAL :: LPHASE_NV, LPHASE2
!-----------------------------------------------------------------------
      IF (LTRANSPOSE) THEN
         IC = IRSAV
         IR = ICSAV
      ELSE
         IC = ICSAV
         IR = IRSAV
      ENDIF

      ATWINV = 1.D0/EMN
      IBUG1 = 0
      
      !IF (.NOT.LTRANSPOSE) THEN
      ! ! The first COLUMN generated by symmetry-ordered-CSF ICC
      ! ! FLEXIBLE: ICC: 10p- 11p-, IC0: 4p- 5p-
      ! IC0 = ICTOT + 1
      ! !The first ROW generated by symmetry-ordered-CSF IRR
      ! ! IRR: 11p- 11p+, IR0: 4p- 4p+, OR,
      ! ! IRR: 11s  11p-, IR0: 4s  4p-
      ! IR0 = IRTOT + 1
      !ELSE
      ! IR0 = ICTOT + 1
      ! IC0 = IRTOT + 1
      !ENDIF


!   Set all matrix elements to zero
      !EMTBLOCK = 0.0D0
      TSHELL = 0.D0
      FLAGL = .FALSE.
      FLAGU = .FALSE.
      FLAGNONE = .TRUE.
      NDIFF = 0

! Number of symmetry-ordered orbs for the IC- and IR-th symmetry-ordered-CSFs
      NORBCOL  = NTYPE(6,IC) - NTYPE(3,IC) + 1
      NORBROWL = NTYPE(4,IR) - NTYPE(3,IR) + 1
      NORBROWU = NTYPE(6,IR) - NTYPE(5,IR) + 1

      IF (NTYPE(3,IC).EQ.NTYPE(3,IR)) THEN
        FLAGL = .TRUE.
        NDIFF = NTYPE(4,IR) - NTYPE(4,IC)
      ENDIF
      IF (NTYPE(3,IC).EQ.NTYPE(5,IR)) THEN
        FLAGU = .TRUE.
        NDIFF = NTYPE(4,IR) - NTYPE(6,IC) 
      ENDIF
      IF (FLAGL.OR.FLAGU) FLAGNONE = .FALSE.

      ! Smallest list version:  
      ! Buiding the FICTIOUTS CSF as needed.
      ! Always only ONE orbital is shifted, hence call FICTIOUS_CSF(2, 
      IF (FLAGL) THEN
        ! K = I
        ! (Core A) ns 5p (IR)        --  (Core B) 6s 7s (IC)   ==> 
        ! (Core A) 6s 5p (IRFICT)    --  (Core B) 6s 7s (IC)
        CALL FICTIOUS_CSF(2, IRFICT, IR, NTYPE(4,IC), NTYPE(4,IR),0,0)
        IRORBIF(1,1) = IRFICT
        IRORBIF(2,1) = NTYPE(4,IC)
        IRORBIF(3,1) = NTYPE(6,IR)

        ! K = J
        ! (Core A) ns 5p (IR)        --  (Core B) 6s 7s (IC)   ==> 
        ! (Core A) 7s 5p (IRFICT+1)  --  (Core B) 6s 7s (IC)
        CALL FICTIOUS_CSF(2, IRFICT+1, IR, NTYPE(6,IC), NTYPE(4,IR),0,0)
        IRORBIF(1,2) = IRFICT+1
        IRORBIF(2,2) = NTYPE(6,IC)
        IRORBIF(3,2) = NTYPE(6,IR)

        ! K /= I AND K /= J
        IF (NORBROWL.GE.3 .OR. NORBCOL.GE.3) THEN
          IF (NORBROWL .GT. NORBCOL) THEN
        ! (Core A) 8s 5p (IR)        --  (Core B) 6s 7s (IC)   
        ! No shift needed.
            IRORBIF(1,3) = IR
            IRORBIF(2,3) = NTYPE(4,IR)
            IRORBIF(3,3) = NTYPE(6,IR)
          ELSE
        ! (Core A) ns 5p (IR)        --  (Core B) 6s 7s (IC)   ==> 
        ! (Core A) 4s 5p (IRFICT+2)  --  (Core B) 6s 7s (IC)
            CALL FICTIOUS_CSF(2, IRFICT+2, IR, NTYPE(3,IC), NTYPE(4,IR),0,0)
            IRORBIF(1,3) = IRFICT+2
            IRORBIF(2,3) = NTYPE(3,IC)
            IRORBIF(3,3) = NTYPE(6,IR)
          ENDIF
        ENDIF
      ENDIF

      IF (FLAGU) THEN
        ! L = I
        ! (Core A) 5s np  (IR)       --  (Core B) 6p 7p (IC)   ==> 
        ! (Core A) 5s 6p (IRFICT)    --  (Core B) 6p 7p (IC)
        CALL FICTIOUS_CSF(2, IRFICT, IR, NTYPE(4,IC), NTYPE(6,IR),0,0)
        IRORBIF(1,1) = IRFICT
        IRORBIF(2,1) = NTYPE(4,IR)
        IRORBIF(3,1) = NTYPE(4,IC)

        ! L = J
        ! (Core A) 5s 5p (IR)        --  (Core B) 6p 7p (IC)   ==> 
        ! (Core A) 5s 7p (IRFICT+1)  --  (Core B) 6p 7p (IC)
        CALL FICTIOUS_CSF(2, IRFICT+1, IR, NTYPE(6,IC), NTYPE(6,IR),0,0)
        IRORBIF(1,2) = IRFICT+1
        IRORBIF(2,2) = NTYPE(4,IR)
        IRORBIF(3,2) = NTYPE(6,IC)

        ! K /= I AND K /= J
        IF (NORBROWU.GE.3 .OR. NORBCOL.GE.3) THEN
          IF (NORBROWU .GT. NORBCOL) THEN
        ! (Core A) 5s 8p (IR)        --  (Core B) 6p 7p (IC)   
        ! No shift needed.
            IRORBIF(1,3) = IR
            IRORBIF(2,3) = NTYPE(4,IR)
            IRORBIF(3,3) = NTYPE(6,IR)
          ELSE
        ! (Core A) 5s np (IR)        --  (Core B) 6p 7p (IC)   ==> 
        ! (Core A) 4s 4p (IRFICT+2)  --  (Core B) 6p 7p (IC)
            CALL FICTIOUS_CSF(2, IRFICT+2, IR, NTYPE(3,IC), NTYPE(6,IR),0,0)
            IRORBIF(1,3) = IRFICT+2
            IRORBIF(2,3) = NTYPE(4,IR)
            IRORBIF(3,3) = NTYPE(3,IC)
          ENDIF
        ENDIF
      ENDIF

! No one-body operators contribution for type 3 - 4
      IF (LPRINT) &
        CALL PRINTLABELV(0, IC, IR, 34, 0, 0, 0, 0.d0)

! One more RKCO_GG call to deal with the 'PHASE-FACTOR' problem
! MTYPE = 1 is partially removed according to LPHASE_NV, LPHASE2
      LPHASE_NV = .FALSE.
      LPHASE2 = .FALSE.

!BE  MTYPE=  0  ICW=     677  ICW*3+5=    2036  IRW=     845  IRW*3+5=      2540  MatrixblockXX= 34
!    IR0=    2921  IR0*3+5=    8768  IRE=    2936  IRE*3+5=    8813
!    IC0=    1403  IC0*3+5=    4214  ICE=    1408  ICE*3+5=    4229
!TB  MTYPE=  2  ICW=     677  ICW*3+5=    2036  IRW=    3627  IRW*3+5=     10886  MatrixblockXX= 34
!    IVCOEF=          1          2
!    Label1=          3          3
!    Label2=         33         33
!    Label3=          8         25
!    Label4=         25          8
!    Label5=          1          1
!    Coeff = -3.600E-01  3.600E-01
!TB  MTYPE=  1: NVCOEF = 0 

!BE  MTYPE=  0  ICW=    1006  ICW*3+5=    3023  IRW=     574  IRW*3+5=     1727  MatrixblockXX= 34
!    IR0=     667  IR0*3+5=    2006  IRE=     682  IRE*3+5=    2051
!    IC0=    3711  IC0*3+5=   11138  ICE=    3716  ICE*3+5=   11153
!TB  MTYPE=  1  ICW=    1006  ICW*3+5=    3023  IRW=    3628  IRW*3+5=    10889  MatrixblockXX= 34
!    IVCOEF=          1
!    Label1=          4
!    Label2=         12
!    Label3=          1
!    Label4=         17
!    Label5=          1
!    Coeff =  1.925E-01
!TB  MTYPE=  2: NVCOEF = 0

! The MTYPE = 1 and 2 loops have to be retained as shown above. 

      DO MTYPE = 1, 2
       NVCOEF = 0
! ENONSYM that does not involve the symmetry-ordered orbital. 
       ENONSYM = 0.D0
       IF (MTYPE.EQ.1) THEN
        ! < K L | h12 | I J>, IF (FLAGL) K = J / IF (FLAGU) L = J
        IF (FLAGNONE) THEN
         ICW = IC
         IRW = IR
         CALL RKCO_GG (ICW, IRW, CORD, INCOR, 1)
        ELSE
          ! Remove partially MTYPE = 1 loop
          !IF (LPHASE_NV .OR. (.NOT.LPHASE2)) CYCLE

          IF (FLAGL) THEN
            IF (NORBROWL.LT.2) CYCLE
            ! IRW (5p- 4p+), ICW (4p- 5p-) : K = J 
            ICW = IC
            IRW = 2
          ELSEIF (FLAGU) THEN
            IF (NORBROWU.LT.2) CYCLE
            ! IRW (4s- 5p-), ICW (4p- 5p-) : L = J
            ICW = IC
            IRW = 2
          ENDIF
          CALL RKCO_GG (ICW, IRORBIF(1,IRW), CORD, INCOR, 1)
        ENDIF
       ELSE
        IF (FLAGNONE) CYCLE ! WITHOUT SAME symmetry-ordered ORB
        ! < K L | h12 | I J>, IF (FLAGL) K = I / IF (FLAGU) L = I
        ! IR0 (4s 4p- / 4p- 4p+), IC0 (4p- 5p-) 
        ICW = IC 
        IRW = 1
        ! K = I / L = I
        CALL RKCO_GG (ICW, IRORBIF(1,IRW), CORD, INCOR, 1)

       ENDIF

       !! There is no contributions within MTYPE = 2 loop, then the MTYPE
       !! = 1 loop is dicarded later. 
       !IF ((FLAGL.OR.FLAGU) .AND. MTYPE.EQ.2 .AND. NVCOEF.EQ.0) &
       !  LPHASE_NV = .TRUE.

       IF (LPRINT .AND. (FLAGL.OR.FLAGU) .AND. NVCOEF.GT.0) &
         CALL PRINTLABELV(2, ICW, IRORBIF(1,IRW), 34, MTYPE, 0, 0, 0.d0)
       IF (NVCOEF .GT. 0) LTRANSFER = .TRUE.
       DO IV = 1, NVCOEF
        VCOEFF = COEFF(IV)
        IF (DABS (VCOEFF) .LE. CUTOFF) CYCLE
        NCTEC = NCTEC + NTYPE(2,IC) 

! Determine the position of the symmetry-ordered orbitals
        LABV=LABEL(1:6, IV)
        CALL ANALABV(IC, IR, IV)

        IF (NSYMCR .EQ. 0) THEN 
! There is no symmetry-ordered orbs for this interact pairs. It is common for
! those generated by the IC and IR symmetry-ordered CSF. It should not occur 
! for type 1 - 2, 3, 4, 5; 2-3, 4, 5; 3-4, 5; and 4-5 matrix elements. 
         WRITE(*,'(a3, i7, 2x, i7, 2x, a5, 5i3)')                    &
               'IC=', IC, 'IR=', IR, 'LABV=', LABV(1:5)
         STOP 'Warning!!! NSYMCR ERROR ***0***'

        ELSEIF (NSYMCR .EQ. 1) THEN 
         WRITE(*,'(a3, i7, 2x, a3, i7, 2x, a5, 5i3)')                &
              'IC=', IC, 'IR=', IR, 'LABV=', LABV(1:5)
         STOP 'Warning!!! NSYMCR ERROR ***1***'

! Matrixelement between Type 3 - 4 
! Loop for symmetry-ordered-orbitals
        ELSEIF (NSYMCR .EQ. 2) THEN 
         ! [core] 10p 11p -- (core) 10p- 11p. 
         IF (NSYMCOL.NE.NSYMROW .OR. (FLAGL.EQV.FLAGU))              &
         THEN
           WRITE(*,'(a3, i7, 2x, a3, i7, 2x, a5, 5i3)')              &
              'IC=', IC, 'IR=', IR, 'LABV=', LABV(1:5)
           WRITE(*,*)'FLAGL, FLAGU=',FLAGL, FLAGU
           STOP 'Warning!!! NSYMCR ERROR ***2***'
         ENDIF

         ! There is contributions involving two symmetry-ordered-orbitals within
         ! MTYPE = 2 loop, then MTYPE = 1 should be called to deal with
         ! the PHASE FACTOR. 
         !IF (MTYPE.EQ.2) LPHASE2 = .TRUE.

         N = 0
         DO I = 1, NORBCOL-1
          DO J = I + 1, NORBCOL
           N = N + 1
           M = 0
           DO K = 1, NORBROWL
            DO L = 1, NORBROWU
             M = M + 1 
             ! FULL MATRIX NEEDED
             IF (FLAGL) THEN
               IF (K.EQ.I .AND. MTYPE.EQ.2) THEN 
                LABV(IPSYM(1)) = NTYPE(3, IC) + J - 1
                LABV(IPSYM(2)) = NTYPE(5, IR) + L - 1
                CALL twobody_DC_SMS(ATWINV, VCOEFF, EMTTMP)
                EMTBLOCK(M,N) = EMTBLOCK(M,N) + EMTTMP
               ELSEIF (K.EQ.J .AND. MTYPE.EQ.1) THEN
                LABV(IPSYM(1)) = NTYPE(3, IC) + I - 1
                LABV(IPSYM(2)) = NTYPE(5, IR) + L - 1
                CALL twobody_DC_SMS(ATWINV, VCOEFF, EMTTMP)
                EMTBLOCK(M,N) = EMTBLOCK(M,N) + EMTTMP
               ENDIF
             ELSEIF (FLAGU) THEN
               IF (L.EQ.I .AND. MTYPE.EQ.2) THEN
                 LABV(IPSYM(1)) = NTYPE(3, IC) + J - 1
                 LABV(IPSYM(2)) = NTYPE(3, IR) + K - 1
                 CALL twobody_DC_SMS(ATWINV, VCOEFF, EMTTMP)
                 EMTBLOCK(M,N) = EMTBLOCK(M,N) + EMTTMP
               ELSEIF (L.EQ.J .AND. MTYPE.EQ.1) THEN
                 LABV(IPSYM(1)) = NTYPE(3, IC) + I - 1
                 LABV(IPSYM(2)) = NTYPE(3, IR) + K - 1
                 CALL twobody_DC_SMS(ATWINV, VCOEFF, EMTTMP)
                 EMTBLOCK(M,N) = EMTBLOCK(M,N) + EMTTMP
               ENDIF
             ENDIF

            ENDDO
           ENDDO
          ENDDO
         ENDDO

          ELSEIF (NSYMCR .EQ. 3) THEN
           WRITE(*,'(a3, i7, 2x, a3, i7, 2x, a5, 5i3)')              &
                'IC=', IC, 'IR=', IR, 'LABV=', LABV(1:5)
           STOP 'Warning!!! NSYMCR ERROR ***3***'

        ELSEIF (NSYMCR .EQ. 4) THEN 
         !IF ((FLAGL.OR.FLAGU) .AND. MTYPE.NE.2) CYCLE
         IF (MTYPE.NE.1) CYCLE
        ! VCOEFF ARE SAME FOR ALL TYPE 3 - 4 pairs
         N=0 
         DO I = 1, NORBCOL-1
          LABV(1) =  NTYPE(3,IC) + I - 1
          DO J = I + 1, NORBCOL 
           LABV(2) =  NTYPE(3,IC) + J - 1
           N = N + 1
           M = 0
           DO K = 1, NORBROWL
            DO L = 1, NORBROWU
             M = M + 1
             ! Full matrix needed
             LABV(3) = NTYPE(3,IR) + K - 1
             LABV(4) = NTYPE(5,IR) + L - 1
             IF (LABEL(3,IV).GT.LABEL(4,IV)) THEN
                LABVTMP = LABV(3)
                LABV(3) = LABV(4)
                LABV(4) = LABVTMP
             ENDIF
             CALL twobody_DC_SMS(ATWINV, VCOEFF, EMTTMP)
             EMTBLOCK(M,N) = EMTBLOCK(M,N) + EMTTMP
            ENDDO
           ENDDO
          ENDDO
         ENDDO

        ENDIF 
       ENDDO
      ENDDO

! No common parts for the diagonal matrixelement 
!
      IBUG1 = 0
!   Accumulate the contribution from the two-electron
!   transverse interaction operator
!
      IF (LTRANS .AND. (INC2.EQ.1)) THEN 
       ENONSYM = 0.0d0
       ICW = IC
       DO MTYPE = 1, 5
        NVCOEF = 0
        ! < K L (IR) | h_br | I J (IC) >
        IF (MTYPE.EQ.1) THEN
         IF (FLAGNONE) CYCLE
         ! IF (FLAGL) K /= I AND K /= J
         ! IF (FLAGU) L /= I AND L /= J
         IF (FLAGL.AND.NORBCOL.LT.3.AND.NORBROWL.LT.3) CYCLE ! At least 3 orbitals in the same sym.  
         IF (FLAGU.AND.NORBCOL.LT.3.AND.NORBROWU.LT.3) CYCLE ! At least 3 orbitals in the same sym.
         IRW = 3
         CALL RKCO_GG (ICW, IRORBIF(1,IRW), BREID, 1, 2)

        ELSEIF (MTYPE.EQ.2) THEN
         IF (.NOT.FLAGL) CYCLE
         ! < K L | h_br | I J >: K = I 
         ! IR0: 4p- 4p+; IC0: 4p- 5p-, K = I
         IRW = 1  
         CALL RKCO_GG (ICW, IRORBIF(1,IRW), BREID, 1, 2)

        ELSEIF (MTYPE.EQ.3) THEN
         IF (.NOT.FLAGU) CYCLE
         ! < (Core A) 10s 9p | h_br | (Core B) 9p 10p > 
         ! < K L | h_br | I J >: L = I 
         ! IR0: 4s 4p- ; IC0: 4p- 5p-, L = I
         IRW = 1
         CALL RKCO_GG (ICW, IRORBIF(1,IRW), BREID, 1, 2)

        ELSEIF (MTYPE.EQ.4) THEN
         IF (FLAGNONE) CYCLE
         ! < K L | h_br | L J >
         ! FLAGL: K = J; FLAGU: L = J
         IF (FLAGL.AND.NORBROWL.LT.2) CYCLE
         IF (FLAGU.AND.NORBROWU.LT.2) CYCLE
         IRW = 2 
         CALL RKCO_GG (ICW, IRORBIF(1,IRW), BREID, 1, 2)

        ELSEIF (MTYPE.EQ.5) THEN
         IF (.NOT.FLAGNONE) CYCLE
         ! < (Core) 9s 10s | h_br | (Core) 9p-10p >
         ICW = IC
         IRW = IR
         CALL RKCO_GG (ICW, IRW, BREID, 1, 2)

        ENDIF

       IF (LPRINT .AND. (FLAGL.OR.FLAGU) .AND. NVCOEF.GT.0) &
         CALL PRINTLABELV(3, ICW, IRORBIF(1,IRW), 34, MTYPE, 0, 0, 0.d0)
        IF (NVCOEF .GT. 0) LTRANSFER = .TRUE.
        DO 10 IV = 1, NVCOEF
          VCOEFF = COEFF(IV)
          IF (DABS (VCOEFF) .GT. CUTOFF) THEN
            NMCBP = NMCBP + NTYPE(2,IC)
! Determine the position of the symmetry-ordered orbitals
            LABV = LABEL(1:6,IV)
            CALL ANALABV(IC, IR, IV)

            IF (NSYMCR .EQ. 0) THEN
! No common part for 3 - 4 matrixelement
               WRITE(*,*)'IC,IR,IV,MTYPE=',IC,IR,IV,MTYPE
               STOP 'Unexpected NSYMCR .EQ. 0 in matrixblock34.f ...'

! Matrixelement between Type 3 - 4, Loop for symmetry-ordered-orbitals
            ELSEIF (NSYMCR .EQ. 1) THEN
             WRITE(*,'(a3, i7, 2x, a3, i7, 2x, a5, 5i3)')            &
                  'IC=', IC, 'IR=', IR, 'LABV=', LABV(1:5)
             STOP 'Warning!!! NSYMCR ERROR ***1***'
             
            ELSEIF (NSYMCR .EQ. 2) THEN
             IF (MTYPE.EQ.1 .OR. MTYPE.EQ.5) THEN
              WRITE(*,'(a3, i7, 2x, a3, i7, 2x, a5, 5i3)')           &
                  'IC=', IC, 'IR=', IR, 'LABV=', LABV(1:5)
              STOP 'Unexpected MTYPE.EQ.1 .OR. MTYPE.EQ.5 B34.f ...'
             ENDIF

             IRPTKL = 0
             ICPTIJ = 0
             IFLAG12 = 0
             !IF (MTYPE.EQ.2) THEN
             !  IF (LABEL(IPSym(1),IV).NE.NTYPE(6,IRW)) IFLAG12 = 1
             !ELSEIF (MTYPE.EQ.3) THEN
             !  IF (LABEL(IPSym(1),IV).NE.NTYPE(4,IRW)) IFLAG12 = 1
             !ELSEIF (MTYPE.EQ.4) THEN
             !  IF (FLAGL.AND.LABEL(IPSym(1),IV).NE.NTYPE(6,IRW))     &
             !    IFLAG12 = 1
             !  IF (FLAGU.AND.LABEL(IPSym(1),IV).NE.NTYPE(4,IRW))     &
             !    IFLAG12 = 1 
             !ENDIF
             IF (MTYPE.EQ.2) THEN
               IF (LABEL(IPSym(1),IV).EQ.NTYPE(6,ICW)) IFLAG12 = 1
             ELSEIF (MTYPE.EQ.3) THEN
               IF (LABEL(IPSym(1),IV).EQ.NTYPE(6,ICW)) IFLAG12 = 1
             ELSEIF (MTYPE.EQ.4) THEN
               IF (FLAGL.AND.LABEL(IPSym(1),IV).EQ.NTYPE(4,ICW))     &
                 IFLAG12 = 1
               IF (FLAGU.AND.LABEL(IPSym(1),IV).EQ.NTYPE(4,ICW))     &
                 IFLAG12 = 1 
             ENDIF
             IF (IFLAG12.EQ.0) THEN
               IRPTKL = IPSym(1)
               ICPTIJ = IPSym(2)
             ELSE
               IRPTKL = IPSym(2)
               ICPTIJ = IPSym(1)
             ENDIF

             N = 0  ! Column index
             DO I = 1, NORBCOL-1
              DO J = I + 1, NORBCOL
                N = N + 1
                M = 0
                DO K = 1, NORBROWL
                 DO L =  1, NORBROWU
                  M = M + 1  ! Row index
                  ! Full matrix needed
                  ! IF (K .GT. I) CYCLE ! IR INNER ALWAYS <= IC INNER ORB
                  ! IF (K .EQ. I .AND. L.GT.J) CYCLE 

                  IF (MTYPE.EQ.2 .AND. FLAGL .AND. K.EQ.I) THEN
                    ! < K L | h_br | L J >: K = I, FLAGL
                    LABV(IRPTKL) = NTYPE(5, IR) + L - 1
                    LABV(ICPTIJ) = NTYPE(3, IC) + J - 1
                    CALL breit_d(IC,IR,IV,VCOEFF,NCORE,ELSTO,EMTTMP)
                    EMTBLOCK(M,N) = EMTBLOCK(M,N) + EMTTMP

                  ELSEIF (MTYPE.EQ.3 .AND. FLAGU .AND. L.EQ.I) THEN 
                    ! < K L | h_br | L J >: L = I, FLAGU
                    LABV(IRPTKL) = NTYPE(3, IR) + K - 1
                    LABV(ICPTIJ) = NTYPE(3, IC) + J - 1
                    CALL breit_d(IC,IR,IV,VCOEFF,NCORE,ELSTO,EMTTMP)
                    EMTBLOCK(M,N) = EMTBLOCK(M,N) + EMTTMP
                  ELSEIF (MTYPE.EQ.4) THEN 
                    IF (FLAGL .AND. K.EQ.J) THEN
                     LABV(IRPTKL) = NTYPE(5, IR) + L - 1
                     LABV(ICPTIJ) = NTYPE(3, IC) + I - 1
                     CALL breit_d(IC,IR,IV,VCOEFF,NCORE,ELSTO,EMTTMP)
                     EMTBLOCK(M,N) = EMTBLOCK(M,N) + EMTTMP
                    ENDIF
                    IF (FLAGU .AND. L.EQ.J) THEN
                     LABV(IRPTKL) = NTYPE(3, IR) + K - 1
                     LABV(ICPTIJ) = NTYPE(3, IC) + I - 1
                     CALL breit_d(IC,IR,IV,VCOEFF,NCORE,ELSTO,EMTTMP)
                     EMTBLOCK(M,N) = EMTBLOCK(M,N) + EMTTMP
                    ENDIF
                  ENDIF 
                 ENDDO
                ENDDO
              ENDDO
             ENDDO

            ELSEIF (NSYMCR .EQ. 3) THEN
             WRITE(*,'(a3, i7, 2x, a3, i7, 2x, a5, 5i3)')            &
                  'IC=', IC, 'IR=', IR, 'LABV=', LABV(1:5)
             STOP 'Warning!!! NSYMCR ERROR ***3***'

            ELSEIF (NSYMCR .EQ. 4) THEN
! Determine the positions of the symmetry-ordered orbitals 
             IRPTK = 0
             IRPTL = 0
             ICPTI = 0
             ICPTJ = 0 
             IF (MTYPE.EQ.1) THEN
              DO I = 1, 4
               !IF (LABEL(I,IV).EQ.NTYPE(4,IRW)) IRPTK = I
               !IF (LABEL(I,IV).EQ.NTYPE(6,IRW)) IRPTL = I
               IF (LABEL(I,IV).EQ.IRORBIF(2,IRW)) IRPTK = I
               IF (LABEL(I,IV).EQ.IRORBIF(3,IRW)) IRPTL = I
               IF (LABEL(I,IV).EQ.NTYPE(4,ICW)) ICPTI = I
               IF (LABEL(I,IV).EQ.NTYPE(6,ICW)) ICPTJ = I
              ENDDO
             ELSEIF (MTYPE.EQ.2) THEN
              DO I = 1, 4
               IF (LABEL(I,IV).EQ.IRORBIF(3,IRW)) IRPTL = I
               IF (LABEL(I,IV).EQ.NTYPE(6,ICW)) ICPTJ = I
               IF (LABEL(I,IV).EQ.NTYPE(4,ICW)) THEN
                IF (IRPTK.EQ.0) THEN
                  IRPTK = I
                ELSE
                  ICPTI = I
                ENDIF
               ENDIF 
              ENDDO
             ELSEIF (MTYPE.EQ.3) THEN
              DO I = 1, 4
               IF (LABEL(I,IV).EQ.IRORBIF(2,IRW)) IRPTK = I
               IF (LABEL(I,IV).EQ.NTYPE(6,ICW)) ICPTJ = I
               IF (LABEL(I,IV).EQ.NTYPE(4,ICW)) THEN
                IF (IRPTL.EQ.0) THEN
                  IRPTL = I
                ELSE
                  ICPTI = I
                ENDIF
               ENDIF
              ENDDO
             ELSEIF (MTYPE.EQ.4) THEN
              IF (FLAGL) THEN
               DO I = 1, 4
                IF (LABEL(I,IV).EQ.IRORBIF(3,IRW)) IRPTL = I
                IF (LABEL(I,IV).EQ.NTYPE(4,ICW)) ICPTI = I
                IF (LABEL(I,IV).EQ.NTYPE(6,ICW)) THEN
                 IF (IRPTK.EQ.0) THEN
                   IRPTK = I
                 ELSE
                   ICPTJ = I
                 ENDIF
                ENDIF
               ENDDO 
              ENDIF
              IF (FLAGU) THEN
               DO I = 1, 4
                IF (LABEL(I,IV).EQ.IRORBIF(2,IRW)) IRPTK = I
                IF (LABEL(I,IV).EQ.NTYPE(4,ICW)) ICPTI = I
                IF (LABEL(I,IV).EQ.NTYPE(6,ICW)) THEN
                 IF (IRPTL.EQ.0) THEN
                   IRPTL = I
                 ELSE
                   ICPTJ = I
                 ENDIF
                ENDIF
               ENDDO
              ENDIF            
             ELSEIF (MTYPE.EQ.5) THEN
              DO I = 1, 4
               IF (LABEL(I,IV).EQ.NTYPE(4,IRW)) IRPTK = I
               IF (LABEL(I,IV).EQ.NTYPE(6,IRW)) IRPTL = I
               IF (LABEL(I,IV).EQ.NTYPE(4,ICW)) ICPTI = I
               IF (LABEL(I,IV).EQ.NTYPE(6,ICW)) ICPTJ = I
              ENDDO
             ENDIF 
 
! Loop over the symmetry-ordered orbitals
             N = 0  ! Column index
             DO I = 1, NORBCOL-1
              DO J = I + 1, NORBCOL
                N = N + 1
                M = 0
                DO K = 1, NORBROWL
                 DO L = 1, NORBROWU
                  M = M + 1  ! Row index
                  ! Re-Implementation as below
                  IF (MTYPE.EQ.1) THEN
                   IF (FLAGL .AND. (K.EQ.I .OR. K.EQ.J)) CYCLE
                     ! Accumulate the contribution for
                     ! FLAGL.AND.K.NE.I.AND.K.NE.J
                   IF (FLAGU .AND. (L.EQ.I .OR. L.EQ.J)) CYCLE
                     ! Accumulate the contribution for
                     ! FLAGU.AND.L.NE.I.AND.L.NE.J
                  ELSEIF (MTYPE.EQ.2) THEN
                   IF (K.NE.I) CYCLE   ! FLAGL = .TRUE.
                     ! Accumulate the contribution for
                     ! FLAGL .AND. K.EQ.I
                  ELSEIF (MTYPE.EQ.3) THEN
                   IF (L.NE.I) CYCLE   ! FLAGU = .TRUE.
                     ! Accumulate the contribution for
                     ! FLAGU .AND. L.EQ.I
                  ELSEIF (MTYPE.EQ.4) THEN
                   IF (FLAGL .AND. K.NE.J) CYCLE
                     ! Accumulate the contribution for
                     ! FLAGL .AND. K.EQ.J
                   IF (FLAGU .AND. L.NE.J) CYCLE
                     ! Accumulate the contribution for
                     ! FLAGU .AND. L.EQ.J
                  ENDIF

                  LABV(IRPTK) = NTYPE(3,IR) + K - 1
                  LABV(IRPTL) = NTYPE(5,IR) + L - 1
                  LABV(ICPTI) = NTYPE(3,IC) + I - 1
                  LABV(ICPTJ) = NTYPE(3,IC) + J - 1
                  CALL breit_d(IC,IR,IV,VCOEFF,NCORE,ELSTO,EMTTMP)
                  EMTBLOCK(M,N) = EMTBLOCK(M,N) + EMTTMP

                  !IF (MTYPE.EQ.1) THEN
                  ! IF ((FLAGL.AND.K.NE.I.AND.K.NE.J) .OR.            &
                  !     (FLAGU.AND.L.NE.I.AND.L.NE.J)) THEN 
                  !  LABV(IRPTK) = NTYPE(3,IR) + K - 1
                  !  LABV(IRPTL) = NTYPE(5,IR) + L - 1
                  !  LABV(ICPTI) = NTYPE(3,IC) + I - 1
                  !  LABV(ICPTJ) = NTYPE(3,IC) + J - 1
                  !  CALL breit_d(IC,IR,IV,VCOEFF,NCORE,ELSTO,EMTTMP)
                  !  EMTBLOCK(M,N) = EMTBLOCK(M,N) + EMTTMP
                  ! ENDIF
                  !ELSEIF (MTYPE.EQ.2) THEN
                  ! IF (FLAGL .AND. K.EQ.I) THEN
                  !  LABV(IRPTK) = NTYPE(3,IR) + K - 1
                  !  LABV(IRPTL) = NTYPE(5,IR) + L - 1
                  !  LABV(ICPTI) = NTYPE(3,IC) + I - 1
                  !  LABV(ICPTJ) = NTYPE(3,IC) + J - 1
                  !  CALL breit_d(IC,IR,IV,VCOEFF,NCORE,ELSTO,EMTTMP)
                  !  EMTBLOCK(M,N) = EMTBLOCK(M,N) + EMTTMP
                  ! ENDIF 
                  !ELSEIF (MTYPE.EQ.3) THEN
                  ! IF (FLAGU .AND. L.EQ.I) THEN
                  !  LABV(IRPTK) = NTYPE(3,IR) + K - 1
                  !  LABV(IRPTL) = NTYPE(5,IR) + L - 1
                  !  LABV(ICPTI) = NTYPE(3,IC) + I - 1
                  !  LABV(ICPTJ) = NTYPE(3,IC) + J - 1
                  !  CALL breit_d(IC,IR,IV,VCOEFF,NCORE,ELSTO,EMTTMP)
                  !  EMTBLOCK(M,N) = EMTBLOCK(M,N) + EMTTMP
                  ! ENDIF
                  !ELSEIF (MTYPE.EQ.4) THEN
                  ! IF ((FLAGL .AND. K.EQ.J) .OR.                     &
                  !      (FLAGU .AND. L.EQ.J)) THEN
                  !  LABV(IRPTK) = NTYPE(3,IR) + K - 1
                  !  LABV(IRPTL) = NTYPE(5,IR) + L - 1
                  !  LABV(ICPTI) = NTYPE(3,IC) + I - 1
                  !  LABV(ICPTJ) = NTYPE(3,IC) + J - 1
                  !  CALL breit_d(IC,IR,IV,VCOEFF,NCORE,ELSTO,EMTTMP)
                  !  EMTBLOCK(M,N) = EMTBLOCK(M,N) + EMTTMP
                  ! ENDIF
                  !ELSEIF (MTYPE.EQ.5) THEN
                  !  LABV(IRPTK) = NTYPE(3,IR) + K - 1
                  !  LABV(IRPTL) = NTYPE(5,IR) + L - 1
                  !  LABV(ICPTI) = NTYPE(3,IC) + I - 1
                  !  LABV(ICPTJ) = NTYPE(3,IC) + J - 1
                  !  CALL breit_d(IC,IR,IV,VCOEFF,NCORE,ELSTO,EMTTMP)
                  !  EMTBLOCK(M,N) = EMTBLOCK(M,N) + EMTTMP
                  !ENDIF 

                 ENDDO
                ENDDO
              ENDDO
             ENDDO
            ENDIF
          ENDIF
   10   CONTINUE
       ENDDO
      ENDIF

!cyc  Transfer EMTBLOCK to EMTSYM 
      IF (LTRANSPOSE) EMTBLOCK=TRANSPOSE(EMTBLOCK)
      IF (LTRANSFER) call transfer_cyc(ICSAV, IRSAV)

      RETURN
      END SUBROUTINE MATRIXBLOCK34
