!***********************************************************************
!                                                                      *
      SUBROUTINE GETINF
!                                                                      *
!   Interactively determines data governing the generation of MCP co-  *
!   efficients.                                                        *
!                                                                      *
!   Call(s) to: [LIB92]: CONVRT, GETYN.                                *
!                                                                      *
!   Written by Farid A. Parpia            Last revision: 19 Dec 1992   *
!   Modified Xinghong He                  Last revision: 30 Jun 1998   *
!                                                                      *
!   File shared (hard link) by mcpmpi, mcpblk                          *
!                                                                      *
!   Updated to treat ICCUT for block                                   *
!                                                                      *
!***********************************************************************
!-----------------------------------------------
!   M o d u l e s
!-----------------------------------------------
      USE CONS_C
      USE orb_C
      USE iccu_C
      USE default_C
      USE iounit_C
      USE mcp_C
      USE hblock_C
! CYC:
      Use csfg_decide_C, ONLY : LSYMD       
!-----------------------------------------------
!   I n t e r f a c e   B l o c k s
!-----------------------------------------------
      USE getyn_I
      IMPLICIT NONE
!-----------------------------------------------
!   L o c a l   V a r i a b l e s
!-----------------------------------------------
      INTEGER :: I
!-----------------------------------------------
!
!   Determine the physical effects specifications
!
      DIAG = .FALSE.
      ICCUT = 0
      IF (DIAG) THEN
         LFORDR = .FALSE.
         do i = 1,100
            ICCUT(i) = 0
         end do
      ELSE
         IF (NDEF /= 0) THEN
            LFORDR = .TRUE.
            WRITE (istde,*) 'Include the CI within the diagonal BLOCK',&
                            ' generated by the same CSFG?'
            LSYMD = GETYN ()
!PERJ
            IF (LSYMD) THEN
              WRITE(739,'(A)') &
                'y  ! CI within diagonal block from CSFs generated by &
                      the same CSFG'
            ELSE
              WRITE(739,'(A)') & 
                'n  ! CI within diagonal block from CSFs generated by &
                      the same CSFG'
            ENDIF
!PERJ END
         ELSE
            LFORDR = .FALSE.
         ENDIF
         IF (LFORDR) THEN
            WRITE (istde,*) 'The contribution of CSFs 1 -- ICCUT will',&
                            ' be treated variationally;'
            WRITE (istde,*) 'the remainder perturbatively; enter ICCUT:'
            do i = 1,nblock
              write(istde,*) 'Give ICCUT for block',i
    1         READ *, ICCUT(i)
!CYC              IF ((ICCUT(i) <= 1).OR.(ICCUT(i) >= ncfblk(i))) THEN
              IF ((ICCUT(i) < 1).OR.(ICCUT(i) > ncfblk(i))) THEN
                WRITE (istde,*) 'GETINF: ICCUT must be greater than 0',&
                                ' and less than ',ncfblk(i)
                WRITE (istde,*) ' please reenter ICCUT:'
                GOTO 1
              ENDIF
!PERJ
              WRITE(739,*) ICCUT(i), '! ICCUT (CSFG) for block',i 
!PERJ END              
            end do
         ENDIF
      ENDIF
      RETURN
      END
