!***********************************************************************
!                                                                      *
      SUBROUTINE SPINANGULAR3  (JASAV, JBSAV, IUNITF, NPOS)
!                                                                      *
!   This routine controls the computation  and storage of the values   *
!   and all indices of the angular coefficients                        *
!                                                                      *
!                                       k                              *
!                   T  (ab)            V  (abcd)                       *
!                    rs                 rs                             *
!                                                                      *
!   k is the multipolarity of a two-particle Coulomb integral. a, b,   *
!   c and d are orbital sequence numbers.  r and s are configuration   *
!   state function indices.                                            *
!                                                                      *
!   Call(s) to: [LIB92]: ALCBUF, ALLOC, CONVRT, DALLOC, RKCO_GG,       *
!                        TNSRJJ.                                       *
!               [GENMCP]: FNDBEG, SETSDA, SORT.                        *
!                                                                      *
!   Written by Farid A. Parpia            Last revision: 28 Sep 1993   *
!   Modified by C. Froese Fischer for block computation.               *
!   Modified by G. Gaigalas and J. Bieron for new spin-angular         *
!   integration                                        01 April 2012   *
!                                                                      *
!***********************************************************************
!                                                                      *
!   Taken from mcpmpi_gg.f90                                           *
!                                                                      *
!   Modify for Spin-Angular integration: (Same TYPE 3 CSFGs)           *
!              <[core A] nk n'k' | H_DC | [core A] nk n'k'>            *
!   [core] is built by labelling symmetries,                           *
!   nks are kappa-ordered orbitals                                     *
!                                                                      *
!   Written by Chongyang Chen, Fudan University, Shanghai, Oct  2023   *
!                                                                      *
!***********************************************************************
!-----------------------------------------------
!   M o d u l e s
!-----------------------------------------------
      USE vast_kind_param, ONLY:  DOUBLE
      USE parameter_def,   ONLY:  NNNW, KEYORB
      USE csfg_memory_man
!-----------------------------------------------
!   I n t e r f a c e   B l o c k s
!-----------------------------------------------
      USE alcbuf_I
      USE rkco_GG_I
!-----------------------------------------------
!   C O M M O N  B L O C K S
!-----------------------------------------------
      USE BUFFER_C,  ONLY: NVCOEF, LABEL, COEFF
      USE DEBUG_C,   ONLY: LDBPA
      USE MCP_C,     ONLY: KMAX, DIAG, LFORDR

      Use symmatrix_mod, KMAXTmp=>KMAX
      Use csfg_tv_C

      IMPLICIT NONE
      EXTERNAL CORD
!-----------------------------------------------
!   D u m m y   A r g u m e n t s
!-----------------------------------------------
      INTEGER  JASAV, JBSAV, IUNITF, NPOS, JA, JB
      !INTEGER  LLISTV(0:KMAX)
      LOGICAL  LINCR
!-----------------------------------------------
!   L o c a l   P a r a m e t e r s
!-----------------------------------------------
      INTEGER, PARAMETER :: KEY = KEYORB
      INTEGER, PARAMETER :: KEYSQ = KEYORB*KEYORB
!-----------------------------------------------
!   L o c a l   V a r i a b l e s
!-----------------------------------------------
      INTEGER :: KK,IA,IB,LAB,IC, &
         ID, NSWAP, ISWAP, LAC, LBD, NTGI
      REAL(DOUBLE), DIMENSION(NNNW) :: TSHELL
      REAL(DOUBLE) :: VCOEFF, TSHELL1

      LOGICAL :: F0INT, LOSCAL, LRKCO
      INTEGER :: NDIFF1,NDIFF2,NORBCOLL,NORBCOLU,NORBROWL,NORBROWU
      INTEGER :: IV, I, J, K, L, M, N, IRW, ICW
!-----------------------------------------------
!
!   LINCR is .TRUE. if NPOS is to be incremented by 1; there
!   is always a diagonal element in each column
!
      IF (LTRANSPOSE) THEN
        JA = JBSAV
        JB = JASAV
      ELSE
        JA = JASAV
        JB = JBSAV
      ENDIF
! Check, it should be diagnoal here, i.e., IRTOT.eq.ICTOT
      IF (IRTOT /= ICTOT) THEN
        WRITE(*,*)"IRTOT /= ICTOT, ",IRTOT, ICTOT
        STOP "IRTOT /= ICTOT in spinangular3.f90 ..."
      ENDIF 

      LOSCAL = .FALSE.
      LRKCO = .FALSE.

      IF (JB /= JA) THEN
         LINCR = .TRUE.
      ELSE
         NPOS = NPOS + 1
         LINCR = .FALSE.
      ENDIF

! CSFs generated by the JB-th CSFG, Row demension
      M = NTYPE(2,JB)
! CSFs generated by the JA-th CSFG, Column demension
      N = NTYPE(2,JA)
! Number of symmetry-ordered orbs of JA-CSFG
      NORBCOLL = NTYPE(4,JA) - NTYPE(3,JA) + 1
      NORBCOLU = NTYPE(6,JA) - NTYPE(5,JA) + 1
! Number of symmetry-ordered orbs of JB-CSFG 
      NORBROWL = NTYPE(4,JB) - NTYPE(3,JB) + 1
      NORBROWU = NTYPE(6,JB) - NTYPE(5,JB) + 1
!
! To use the lowest CSFs pair by default, then if the JB CSFG has one of
! the TWO symmetry-ordered orbitals of JA CSFG, the IRW and ICW meet the
! requirement that they have the same orbital by default. 
!
! V-coefficients involving only labelling orbitals are not output, if
! fictious CSFs are used for diagonal elements, same as spinangular4.f90
! and spinangular5.f90.
!
      IRW = JB
      ICW = JA
      !CALL FICTIOUS_CSF(2, IRFICT+1, JB, NTYPE(3,JB), NTYPE(4,JB), 0, 0)
      !CALL FICTIOUS_CSF(2, IRFICT+2, IRFICT+1, NTYPE(5,JB),NTYPE(6,JB), 0, 0)
      !! Copy IRFICT+2 fictious CSF to IRFICT.
      !CALL FICTIOUS_CSF(2, IRFICT, IRFICT+2, 0, 0, 0, 0)

      !CALL FICTIOUS_CSF(2, ICFICT+1, JA, NTYPE(3,JA), NTYPE(4,JA),0, 0)
      !CALL FICTIOUS_CSF(2, ICFICT+2, ICFICT+1, NTYPE(5,JA), NTYPE(6,JA), 0, 0)
      !! Copy ICFICT+2 fictious CSF to ICFICT.
      !CALL FICTIOUS_CSF(2, ICFICT, ICFICT+2, 0, 0, 0, 0)
!
! There are onebody contributions for diagonal and some off-diagonal
! elements between the diagonal block generated by the JA - JB ( = JA) CSFGs.
!
! Onebody contributions.
!
!  < [Core] K L | [core A] I J> /= 0 
! Set the diagonal, K = I and L = J 
!
      DO I = 1, N
        LNonZero(I,I) = .TRUE.
      ENDDO
!
! The off-diagonal elements with K = I and L /= J,
! and  K /= I but L = J. TSHELL(1) are both 1.0d0 
! without calling ONESCALAR.
! 
      N = 0
      DO I = 1, NORBCOLL
        DO J = 1, NORBCOLU
          N = N + 1
          M = 0
          DO K = 1, NORBROWL
            DO L = 1, NORBROWU
              M = M + 1
              ! Upper-Triangle matrix needed
              IF (K > I) CYCLE 
              IF (K == I .AND. L > J) CYCLE
              IF (K == I .AND. L /= J) LNonZero(M,N) = .TRUE.
              IF (K <  I .AND. L == J) LNonZero(M,N) = .TRUE.
            ENDDO
          ENDDO
        ENDDO
      ENDDO 
!
!   Call the MCP package to generate V coefficients; ac and bd
!   are the density pairs. NVCOEF is initialized here but changed
!   in /rkco/cor[d] via COMMON.
!
      NVCOEF = 0
      CALL RKCO_GG (ICW, IRW, CORD, 1, 1)
      CALL SAVETV(2, JASAV, JBSAV, IUNITF, 1, IA, IB, TSHELL1)
      !IF (NVCOEF > 0) &
      !  CALL PRINTLABELV(2, JA, JB, 3, 0, 0, 0, 0.0d0)
      DO 2 IV = 1, NVCOEF
         VCOEFF = COEFF(IV)
         IF (ABS (VCOEFF) > CUTOFF) THEN
           !IA = LABEL(1,IV)
           !IB = LABEL(2,IV)
           !IC = LABEL(3,IV)
           !ID = LABEL(4,IV)
           !KK = LABEL(5,IV)
           !F0INT=(KK.EQ.0).AND.(IA.EQ.IC).AND.(IB.EQ.ID)
           !IF (.NOT. F0INT) THEN
             IF (.NOT.LRKCO) THEN
               LRKCO = .TRUE.
               ! NRKCO = NRKCO + 1
               LTRANSFER = .TRUE.
               ! The following loops should be further checked by using
               ! ANALABV, if (NSYMCR .EQ. 4) then no modifications
               ! needed.
               DO J = 1, N
                 DO I = 1, J
                   ! Upper-triangle matrix needed
                   LNonZero(I,J) = .TRUE.
                 ENDDO
               ENDDO
             ENDIF

! Swap index to make sure IA <= IC, IB <= ID and record the number
! of swaps
           !  NSWAP = 0
           !  IF (IA > IC) THEN
           !     ISWAP = IC
           !     IC = IA
           !     IA = ISWAP
           !     NSWAP = NSWAP + 1
           !  ENDIF
           !  IF (IB > ID) THEN
           !     ISWAP = ID
           !     ID = IB
           !     IB = ISWAP
           !     NSWAP = NSWAP + 1
           !  ENDIF
           !  IF (LINCR) THEN
           !     NPOS = NPOS + 1
           !     LINCR = .FALSE.
           !  ENDIF
           !  LLISTV(KK) = LLISTV(KK) + 1
           !  LAC = IA * KEY + IC
           !  LBD = IB * KEY + ID
           !  IF (LAC .LT. LBD) THEN
           !     LAB = LAC * KEYSQ + LBD
           !  ELSE
           !     LAB = LBD * KEYSQ + LAC
           !  ENDIF
           !  WRITE (32+KK) JA, NPOS, LAB, VCOEFF
           !ENDIF
         ENDIF
    2 CONTINUE
!
!   All angular coefficients for this pair of CSFs have been
!   generated; update file 30
!
!      IF ((JB .EQ. JA) .OR. (.NOT. LINCR))   &
 

      IF (LTRANSFER) THEN
        IF (LTRANSPOSE) LNonZero = TRANSPOSE(LNonZero)
        CALL TRANSFER_CSFG(JASAV, JBSAV)
      ENDIF

      RETURN
      END SUBROUTINE
