!***********************************************************************
!                                                                      *
      SUBROUTINE SPINANGULAR25 (JASAV, JBSAV, IUNITF, NPOS)
!                                                                      *
!   This routine controls the computation  and storage of the values   *
!   and all indices of the angular coefficients                        *
!                                                                      *
!                                       k                              *
!                   T  (ab)            V  (abcd)                       *
!                    rs                 rs                             *
!                                                                      *
!   k is the multipolarity of a two-particle Coulomb integral. a, b,   *
!   c and d are orbital sequence numbers.  r and s are configuration   *
!   state function indices.                                            *
!                                                                      *
!   Call(s) to: [LIB92]: ALCBUF, ALLOC, CONVRT, DALLOC, RKCO_GG,       *
!                        TNSRJJ.                                       *
!               [GENMCP]: FNDBEG, SETSDA, SORT.                        *
!                                                                      *
!   Written by Farid A. Parpia            Last revision: 28 Sep 1993   *
!   Modified by C. Froese Fischer for block computation.               *
!   Modified by G. Gaigalas and J. Bieron for new spin-angular         *
!   integration                                        01 April 2012   *
!                                                                      *
!***********************************************************************
!                                                                      *
!   Taken from mcpmpi_gg.f90                                           *
!                                                                      *
!   Modify for Spin-Angular integration: (TYPE 2 and TYPE 5 CSFGs)     *
!              <[core A] nk | H_DC | [core B] n'k'^2>                  *
!   [core] is built by labelling symmetries,                           *
!   nk, n'k' are kappa-ordered orbitals                                *
!                                                                      *
!   Written by Chongyang Chen, Fudan University, Shanghai, Oct  2023   *
!                                                                      *
!***********************************************************************
!-----------------------------------------------
!   M o d u l e s
!-----------------------------------------------
      USE vast_kind_param, ONLY:  DOUBLE
      USE parameter_def,   ONLY:  NNNW, KEYORB
      USE csfg_memory_man
!-----------------------------------------------
!   I n t e r f a c e   B l o c k s
!-----------------------------------------------
      USE alcbuf_I
      USE rkco_GG_I
!-----------------------------------------------
!   C O M M O N  B L O C K S
!-----------------------------------------------
      USE BUFFER_C,  ONLY: NVCOEF, LABEL, COEFF
      USE DEBUG_C,   ONLY: LDBPA
      USE MCP_C,     ONLY: KMAX, DIAG, LFORDR

      Use symmatrix_mod, KMAXTmp=>KMAX
      Use csfg_tv_C

      IMPLICIT NONE
      EXTERNAL CORD
!-----------------------------------------------
!   D u m m y   A r g u m e n t s
!-----------------------------------------------
      INTEGER  JASAV, JBSAV, IUNITF, NPOS, JA, JB
      !INTEGER  LLISTV(0:KMAX)
      LOGICAL  LINCR
!-----------------------------------------------
!   L o c a l   P a r a m e t e r s
!-----------------------------------------------
      INTEGER, PARAMETER :: KEY = KEYORB
      INTEGER, PARAMETER :: KEYSQ = KEYORB*KEYORB
!-----------------------------------------------
!   L o c a l   V a r i a b l e s
!-----------------------------------------------
      INTEGER :: KK,IA,IB,LAB,IC, &
         ID, NSWAP, ISWAP, LAC, LBD, NTGI
      REAL(DOUBLE), DIMENSION(NNNW) :: TSHELL
      REAL(DOUBLE) :: VCOEFF, TSHELL1

      LOGICAL :: F0INT, LOSCAL, LRKCO, FLAGU, LSYM1, LSYM3
      INTEGER :: NDIFF1,NDIFF2,NORBCOL,NORBROW
      INTEGER :: IV, I, J, K, L, M, N, IRW, ICW
!-----------------------------------------------
!
!   LINCR is .TRUE. if NPOS is to be incremented by 1; there
!   is always a diagonal element in each column
!
      IF (LTRANSPOSE) THEN
        JA = JBSAV
        JB = JASAV
      ELSE
        JA = JASAV
        JB = JBSAV
      ENDIF

      LOSCAL = .FALSE.
      LRKCO = .FALSE.

      IF (JB /= JA) THEN
         LINCR = .TRUE.
      ELSE
         NPOS = NPOS + 1
         LINCR = .FALSE.
      ENDIF

! CSFs generated by the JB-th CSFG, Row demension
      M = NTYPE(2,JB)
! CSFs generated by the JA-th CSFG, Column demension
      N = NTYPE(2,JA)
! Number of symmetry-ordered orbs of JA-CSFG
      NORBCOL = NTYPE(4,JA) - NTYPE(3,JA) + 1
! Number of symmetry-ordered orbs of JB-CSFG 
      NORBROW = NTYPE(4,JB) - NTYPE(3,JB) + 1
! Check
      IF (NORBCOL /= N .OR. NORBROW /= M) THEN
        WRITE(*,*)"NORBCOL /= N .OR. NORBROW /= M, ", &
                  NORBCOL, N, NORBROW, M
        STOP "NORBCOL /= N .OR. NORBROW /= M IN SpinAngular25.f90 ..."
      ENDIF
!
! There is possible onebody contributions between TYPE 2 - 5 CSFGs.
!
      IRW = IRFICT
      ICW = ICFICT
      FLAGU = .FALSE.
      IF (NTYPE(3,JA) .EQ. NTYPE(3,JB)) THEN
        FLAGU = .TRUE.
      ENDIF
!
! Forcing the fictious CSFs with the lowest n value.
!
      CALL FICTIOUS_CSF(2, IRFICT, JB, NTYPE(3,JB), NTYPE(4,JB), 0, 0)
      CALL FICTIOUS_CSF(5, ICFICT, JA, NTYPE(3,JA), NTYPE(4,JA), 0, 0)

      IF (.NOT. FLAGU) GOTO 101
!
! Onebody contributions.
!
!        
      IF (JB /= JA) THEN
        ! Compute T coefficients
        IA = 0
        IB = 0
        CALL ONESCALAR(ICW, IRW, IA, IB, TSHELL)
        CALL SAVETV(1, JASAV, JBSAV, IUNITF, 1, IA, IB, TSHELL(1))
        IF (IA /= 0 .AND. IA /= IB .AND.       &
               ABS (TSHELL(1)) > CUTOFF) THEN
           IF (.NOT. LOSCAL) THEN
             LOSCAL = .TRUE.
             ! NONESCALAR = NONESCALAR + 1
             LTRANSFER = .TRUE.

             ! Semi-Diagonal matrixelement needed
             DO I = 1, min(M,N)
               LNonZero(I,I) = .TRUE.
             ENDDO
           ENDIF
!
! TSHELL(1) should be used for the min(M,N) diagonal matrix elements
! without any changes, as IA and IB are both labelling orbitals. 
!           
           !NPOS = NPOS + 1
           !LINCR = .FALSE.
           !LLISTT = LLISTT + 1
           !LAB = MIN (IA,IB) * KEY + MAX (IA,IB)
            
        ENDIF
      ENDIF

101   CONTINUE
!
!   Call the MCP package to generate V coefficients; ac and bd
!   are the density pairs. NVCOEF is initialized here but changed
!   in /rkco/cor[d] via COMMON.
!
      LSYM1 = .FALSE.
      LSYM3 = .FALSE.
      NVCOEF = 0
      CALL RKCO_GG (ICW, IRW, CORD, 1, 1)
      CALL SAVETV(2, JASAV, JBSAV, IUNITF, 1, IA, IB, TSHELL1)
      DO 2 IV = 1, NVCOEF
         VCOEFF = COEFF(IV)
         IF (ABS (VCOEFF) > CUTOFF) THEN
           !IA = LABEL(1,IV)
           !IB = LABEL(2,IV)
           !IC = LABEL(3,IV)
           !ID = LABEL(4,IV)
           !KK = LABEL(5,IV)
           NSYMCR = COUNT(LABEL(1:4,IV) > NORBGEN)
           !F0INT=(KK.EQ.0).AND.(IA.EQ.IC).AND.(IB.EQ.ID)
           !IF (.NOT. F0INT) THEN
             IF (.NOT.LRKCO) THEN
               LRKCO = .TRUE.
               ! NRKCO = NRKCO + 1
               LTRANSFER = .TRUE.
             ENDIF
             IF (NSYMCR == 3 .AND. (.NOT. LSYM3)) THEN 
               ! Full matrix nonzero
               LSYM3 = .TRUE.
               LNonZero(1:M,1:N) = .TRUE.
             ELSEIF (NSYMCR == 1 .AND. (.NOT. LSYM1)) THEN
               ! Semi-diagonal matrixelement is nonzero
               LSYM1 = .TRUE.
               DO I = 1, MIN(M,N)
                 LNonZero(I,I) = .TRUE.
               ENDDO
             ENDIF

! Swap index to make sure IA <= IC, IB <= ID and record the number
! of swaps
           !  NSWAP = 0
           !  IF (IA > IC) THEN
           !     ISWAP = IC
           !     IC = IA
           !     IA = ISWAP
           !     NSWAP = NSWAP + 1
           !  ENDIF
           !  IF (IB > ID) THEN
           !     ISWAP = ID
           !     ID = IB
           !     IB = ISWAP
           !     NSWAP = NSWAP + 1
           !  ENDIF
           !  IF (LINCR) THEN
           !     NPOS = NPOS + 1
           !     LINCR = .FALSE.
           !  ENDIF
           !  LLISTV(KK) = LLISTV(KK) + 1
           !  LAC = IA * KEY + IC
           !  LBD = IB * KEY + ID
           !  IF (LAC .LT. LBD) THEN
           !     LAB = LAC * KEYSQ + LBD
           !  ELSE
           !     LAB = LBD * KEYSQ + LAC
           !  ENDIF
           !  WRITE (32+KK) JA, NPOS, LAB, VCOEFF
           !ENDIF
         ENDIF
    2 CONTINUE
!
!   All angular coefficients for this pair of CSFs have been
!   generated; update file 30
!
!      IF ((JB .EQ. JA) .OR. (.NOT. LINCR))   &
 

      IF (LTRANSFER) THEN
        IF (LTRANSPOSE) LNonZero = TRANSPOSE(LNonZero)
        CALL TRANSFER_CSFG(JASAV, JBSAV)
      ENDIF

      RETURN
      END SUBROUTINE SPINANGULAR25
