#!/bin/sh
set -x

# 3. For Dirac-Fock calculation

cp n3.g rcsfg.inp
cp n3.l rlabel.inp
mpirun -np 1 rangular_csfg_mpi > out_rangular_n3 <<S4
y
S4

#  Get initial estimates of wave functions
rwfnestimate_csfg > /dev/null 2>&1 <<S5
y
3
*
S5

# Perform self-consistent field calculations
mpirun -np 1 rmcdhf_csfg_mpi > out_rmcdhf_n3 <<S6
y
1-5
1-2
1-3
1-5
1-7
1-5
1-2
1-3
1-2
1
5
*
*
100
S6

# Perform additional RMCDHF calculation to ensure convergence
mv rwfn.out rwfn.inp
mpirun -np 1 rmcdhf_csfg_mpi > out_rmcdhf_n3 <<S6
y
1-5
1-2
1-3
1-5
1-7
1-5
1-2
1-3
1-2
1
5
*
*
100
S6

# Save the result to n3
rsave_csfg n3

# transform to LSJ-coupling
jj2lsj_csfg  > /dev/null 2>&1 <<S1
n3
n
y
y
S1

rlevels_csfg n3.m  > n3.lev
rm rcsfg.inp rlabel.inp rwfn.out rwfn.inp rcsf.out > /dev/null 2>&1
