      MODULE matrix_csfg_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  16:52:04   1/ 6/07
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE matrix_csfg (eol, dvdfirst)
      logical, INTENT(IN) ::  eol, dvdfirst
      END SUBROUTINE
      END INTERFACE
      END MODULE
