      MODULE setcof_xy_csfg_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  14:21:02   1/ 5/07
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      !SUBROUTINE setcof_xy_csfg (IFLAG, IA, IB, IC, ID, K, SUMV)
      SUBROUTINE setcof_xy_csfg (IFLAG, LAB0, K, SUMV)
      USE vast_kind_param,  ONLY: DOUBLE, BYTE

      LOGICAL, INTENT(IN)       :: IFLAG
      INTEGER, INTENT(IN)       :: K
      INTEGER, INTENT(IN)       :: LAB0
      !INTEGER(BYTE), INTENT(IN)       :: IA, IB, IC, ID
      REAL(DOUBLE), INTENT(IN)  :: SUMV
      END SUBROUTINE
      END INTERFACE
      END MODULE
