      MODULE setham_pot_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  14:23:52   1/ 5/07
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE setham_pot (EOL, JBLOCK)
      USE vast_kind_param, ONLY: LONG
      LOGICAL, INTENT(IN) :: EOL
      INTEGER, INTENT(IN) :: JBLOCK
      END SUBROUTINE
      END INTERFACE
      END MODULE
