      MODULE setmcp_csfg_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  11:01:42   1/ 5/07
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
!cjb  myid, nprocs = NOT args
      SUBROUTINE setmcp_csfg (IFLAG, NCORE, NBLKIN, IDBLK, FILEHEAD)
      INTEGER, INTENT(IN)   :: IFLAG
      INTEGER               :: NCORE
      INTEGER, INTENT(IN)   :: NBLKIN
      CHARACTER (LEN = 8), DIMENSION(*) :: IDBLK
      CHARACTER (LEN = *), INTENT(IN)   :: FILEHEAD
!...This routine performs I/O.
      END SUBROUTINE
      END INTERFACE
      END MODULE
