#!/bin/sh

set -x

# Generate Full CSFGs 
rcsfggenerate_csfg <<EOF3
0
1s(2,i)2s(2,*)
1s(2,i)2p(2,*)
1s(2,i)2s(1,*)3s(1,*)
1s(2,i)2s(1,*)3d(1,*)

3s,3p,3d
0,6
0
y
1s(2,i)2s(1,*)2p(1,*)
1s(2,i)2s(1,*)3p(1,*)
1s(2,i)2p(1,*)3s(1,*)

3s,3p,3d
0,4
0
y
1s(2,*)2s(2,*)
1s(2,*)2p(2,*)
1s(2,*)2s(1,*)3s(1,*)
1s(2,*)2s(1,*)3d(1,*)

9s,9p,9d,9f,9g
0,6
2
y
1s(2,*)2s(1,*)2p(1,*)
1s(2,*)2s(1,*)3p(1,*)
1s(2,*)2p(1,*)3s(1,*)

9s,9p,9d,9f,9g
0,4
2
n
EOF3

mv rcsfg.out  rcsfg.inp
mv rlabel.out rlabel.inp

# Condense CSF(G)s by rcsfginteract_csfg
rcsfginteract_csfg <<EOF
1
EOF
mv rcsfg.out Full_n.g

# Split into  Full_n4.g, Full_n5.g, Full_n6.g, Full_n7.g, Full_n8.g, Full_n9.g
# Also obtain Full_n4.l, Full_n5.l, Full_n6.l, Full_n7.l, Full_n8.l, Full_n9.l
rcsfgsplit_csfg <<EOF5
Full_n
6
4s,4p,4d,4f
4
5s,5p,5d,5f,5g
5
6s,6p,6d,6f,6g
6
7s,7p,7d,7f,7g
7
8s,8p,8d,8f,8g
8
9s,9p,9d,9f,9g
9
EOF5
