      MODULE lodcsl_Full_I
      INTERFACE
      SUBROUTINE lodcsl_Full (NEXT_BLOCKF)
!      INTEGER NNNW
!      PARAMETER(NNNW=214)
      LOGICAL, INTENT(OUT)  :: NEXT_BLOCKF
      END SUBROUTINE
      END INTERFACE
      END MODULE
