#!/bin/sh
set -x

#   4.  Get results for n=4,5,6,7,8,9

for n in 4 5 6 7 8 9
do
   (cp n${n}.c rcsf.inp

#  Get angular data
echo 'rm MPI_TMP/* -rf'
rm MPI_TMP/* -rf

mpirun -np 16 rangular_mpi > out_rangular_n${n}<<S4
y
S4
du  -h MPI_TMP
ls -lh MPI_TMP/000

# Get initial estimates of wave functions
m=`expr $n - 1`
echo m=$m n=$n
rwfnestimate > /dev/null 2>&1 <<S5
y
1
n${m}.w
*
3
*
S5

# Perform self-consistent field calculations
mpirun -np 16 rmcdhf_mem_mpi > out_rmcdhf_n${n}<<S6
y
1-4
1-3
1-3
1-6
1-4
1-3
1-1
5
${n}*

100
S6

## Perform additional RMCDHF calculation to ensure convergence
#mv rwfn.out rwfn.inp
#mpirun -np 16 rmcdhf_mem_mpi > out_rmcdhf_n${n}<<S6
#y
#1-4
#1-3
#1-3
#1-6
#1-4
#1-3
#1-1
#5
#${n}*
#
#100
#S6

rsave n${n}

# transform to LSJ-coupling
jj2lsj_2024 > /dev/null 2>&1 <<S1
n${n}
n
y
y
S1

rlevels n${n}.m > n${n}.lev

   echo)
done

#  Perform Breit-correction using CI for n=9. First copy to other file names

n=9
cp n${n}.c n${n}CI.c
cp n${n}.w n${n}CI.w


mpirun -np 16 rci_mpi > out_rci_n${n}<<S7
y                  #Default settings?
n${n}CI
y                  #Include contribution of H (Transverse)?
y                  #Modify all transverse photon frequencies?
1.0d-6             #WFACT
y                  #Include H (Vacuum Polarisation, term 2 and 4)?
n                  #Include H (Normal Mass Shift)?
n                  #Include H (Specific Mass Shift)?
y                  #Estimate self-energy?
3                  #NQEDMAX, !!! Largest n quantum number of the sectroscopy orbital !!!!
1-4
1-3
1-3
1-6
1-4
1-3
1-1
S7

# transform to LSJ-coupling
jj2lsj_2024 > /dev/null 2>&1 <<S1
n${n}CI
y
y
y
S1

rlevels n${n}CI.cm > n${n}CI.clev
rm rcsf.inp rwfn.inp rwfn.out
