#!/bin/sh
set -x

#   4.  Get results for odd n=3,4,5,6

for n in 3 4 5 6
do
   (cp odd${n}.g rcsfg.inp

cp odd${n}.l rlabel.inp

#  Get angular data
rm MPI_TMP/* -rf
mpirun -np 4 rangular_csfg_mpi > out_rangular_odd${n}<<S4
y
S4
du -h  MPI_TMP
ls -lh MPI_TMP/000

# Get initial estimates of wave functions
m=`expr $n - 1`
echo m=$m n=$n
rwfnestimate_csfg > /dev/null 2>&1 <<S5
y
1
odd${m}.w
*
3
*
S5

# Perform self-consistent field calculations
mpirun -np 4 rmcdhf_csfg_mpi > out_rmcdhf_odd${n}<<S6
y
1
1
5
${n}*

100
S6

# Perform additional RMCDHF calculation to ensure convergence
mv rwfn.out rwfn.inp
mpirun -np 4 rmcdhf_csfg_mpi > out_rmcdhf_odd${n}<<S6
y
1
1
5
${n}*

100
S6

rsave_csfg odd${n}

# transform to LSJ-coupling
jj2lsj_csfg  > /dev/null 2>&1 <<S1
odd${n}
n
y
y
S1

   echo)
done

#  Perform Breit-correction using CI for n=6. First copy to other file names

n=6
cp odd${n}.g oddCI${n}.g
cp odd${n}.l oddCI${n}.l
cp odd${n}.w oddCI${n}.w

# rci_csfg_mpi will output automatically oddCI${n}.c
mpirun -np 4 rci_csfg_mpi > out_rci_odd<<S7
y                  #Default settings?
oddCI${n}
y                  #Include contribution of H (Transverse)?
y                  #Modify all transverse photon frequencies?
1.0d-6             #WFACT
n                  #Limit the Breit contributions by n?
15                 #Discard Breit interaction for above n:
n                  #Limit the Breit contributions by l?
14                 #Discard Breit interaction for above l:
y                  #Include H (Vacuum Polarisation, term 2 and 4)?
n                  #Include H (Normal Mass Shift)?
n                  #Include H (Specific Mass Shift)?
y                  #Estimate self-energy?
2                  #NQEDMAX, !!! Largest n quantum number of the sectroscopy orbital !!!!
8                  #MaxMemPerProcs, in GB (INTEGER)
1   
1   
S7

# transform to LSJ-coupling
jj2lsj_csfg > /dev/null 2>&1 <<S1
oddCI${n}
y
y
y
S1

#   4.  Get results for even n=3,4,5,6

for n in 3 4 5 6
do
   (cp even${n}.g rcsfg.inp

cp even${n}.l rlabel.inp

#  Get angular data
echo 'rm MPI_TMP/* -rf'
rm MPI_TMP/* -rf
mpirun -np 4 rangular_csfg_mpi > out_rangular_even${n}<<S4
y
S4
du  -h MPI_TMP
ls -lh MPI_TMP/000

# Get initial estimates of wave functions
m=`expr $n - 1`
echo m=$m n=$n
rwfnestimate_csfg > /dev/null 2>&1 <<S5
y
1
even${m}.w
*
3
*
S5

# Perform self-consistent field calculations
mpirun -np 4 rmcdhf_csfg_mpi > out_rmcdhf_even${n}<<S6
y
1,2,3
1,2,3
1,2
5
${n}*

100
S6

# Perform additional RMCDHF calculation to ensure convergence
mv rwfn.out rwfn.inp
mpirun -np 4 rmcdhf_csfg_mpi > out_rmcdhf_even${n}<<S6
y
1,2,3
1,2,3
1,2
5
${n}*

100
S6

rsave_csfg even${n}

# transform to LSJ-coupling
jj2lsj_csfg > /dev/null 2>&1 <<S1
even${n}
n
y
y
S1

rlevels_csfg odd${n}.m even${n}.m > n${n}.lev

   echo)
done

#  Perform Breit-correction using CI for n=6

n=6
cp even${n}.g evenCI${n}.g
cp even${n}.l evenCI${n}.l 
cp even${n}.w evenCI${n}.w

# rci_csfg_mpi will output automatically evenCI${n}.c
mpirun -np 4 rci_csfg_mpi > out_rci_even<<S7
y                  #Default settings?
evenCI${n}
y                  #Include contribution of H (Transverse)?
y                  #Modify all transverse photon frequencies?
1.0d-6             #WFACT
n                  #Limit the Breit contributions by n?
15                 #Discard Breit interaction for above n:
n                  #Limit the Breit contributions by l?
14                 #Discard Breit interaction for above l:
y                  #Include H (Vacuum Polarisation, term 2 and 4)?
n                  #Include H (Normal Mass Shift)?
n                  #Include H (Specific Mass Shift)?
y                  #Estimate self-energy?
2                  #NQEDMAX, !!! Largest n quantum number of the sectroscopy orbital !!!!
2                  #MaxMemPerProcs, in GB (INTEGER)
1,2,3   
1,2,3   
1,2
S7

# transform to LSJ-coupling
jj2lsj_csfg > /dev/null 2>&1 <<S1
evenCI${n}
y
y
y
S1

rlevels_csfg oddCI${n}.cm evenCI${n}.cm > n${n}CI.clev
rm rcsfg.inp rlabel.inp rwfn.out rwfn.inp rcsf.out
