#=======================================================================
#
# Misc RCI calculations on Mg-like Fe from MR-SD VV+CV+CC expansions
#
# Scripts are provied by the Fudan Atomic Spectroscopy Theory Group 
#                             ****(FASTG)****                     
#
#=======================================================================
# files_gwl: radial wavefunctions were copied from script4/csfg/ calculations
#            the CSFG lists(.g) and the corresponding labeling files (.l) are
#            generated by the script sh_file_c_ci.
# 
# 01_block:       test rci_block_csfg_mpi, test re-run mode
#
# 02_RAC_LBr:     test rmixaccumulate_csfg and limit Breit contributions
#
# 03_RAC_Ext_LBr: test rmixaccumulate_csfg, rcsfgextend_csfg, and limit Breit contributions
#
# !!!!! All the above programs should be found in the environmental variable ${PATH} !!!
# 
#=======================================================================

# Assuming that script4/csfg/CIn[3-9].[gwl] files are obtained:
#cp ../script4/csfg/CIn?.? files_gwl/

# CIn[3-9].w have been copied into files_gwl
# Just generate CIn[3-9].g and .l files:
cd files_gwl/
./sh_files_c_ci
cd ..

cd 01_block
./clean
./sh_ci   > out_sh_ci 2>&1
cd ../

cd 02_RAC_LBr
./clean
./sh_ci   > out_sh_ci 2>&1
cd ../

cd 03_RAC_Ext_LBr
./clean
./sh_ci   > out_sh_ci 2>&1
cd ..

# Wall-Time differences could be seen from the corresponding log-flies

# 01_block should reproduce exactly the results of script4/CIn9.clev
#>>>
# vimdiff ../script4/csfg/CIn9.clev 01_block/CIn9.clev
#>>>

# See the effects by rmixaccumulate_csfg and limit Breit contributions
#>>>
# vimdiff ../script4/csfg/CIn9.clev 02_RAC_LBr/RAC_CIn9.clev
#                10 685 144 CSFs    vs            3 925 070 CSFs
# vimdiff ../script4/csfg/out_rci_CIn9 02_RAC_LBr/out_rci_RAC_CIn9 
#                11 026 seconds     vs            3 278 seconds
#
# vimdiff ../script4/csfg/CIn9.clev 02_RAC_LBr/LBr_RAC_CIn9.clev
#                10 685 144 CSFs    vs            3 925 070 CSFs
# vimdiff ../script4/csfg/out_rci_CIn9 02_RAC_LBr/out_rci_LBr_RAC_CIn9 
#                11 026 seconds     vs            1 777 seconds
#
# vimdiff 02_RAC_LBr/RAC_CIn9.clev 02_RAC_LBr/LBr_RAC_CIn9.clev
#                 3 278 seconds     vs            1 777 seconds
#
# vimdiff ../script4/csfg/CIn9.clev 03_RAC_Ext_LBr/RACn8_CIn9.clev
#                10 685 144 CSFs    vs            3 956 627 CSFs 
# vimdiff ../script4/csfg/out_rci_CIn9 03_RAC_Ext_LBr/out_rci_RACn8_CIn9 
#                11 026 seconds     vs            1 683 seconds
# 
# The effects of different CSF(G) condensations are negligible:
# vimdiff 02_RAC_LBr/LBr_RAC_CIn9.clev 03_RAC_Ext_LBr/RACn8_CIn9.clev
#                 3 925 070 CSFs    vs            3 956 627 CSFs 
#                 1 777 seconds     vs            1 683 seconds
#
#>>>
