#!/bin/sh
set -x

#   4.  Get results for n=4,5,6,7,8,9

for n in 4 5 6 7 8 9
do
   (cp n${n}.g rcsfg.inp

cp n${n}.l rlabel.inp

#  Get angular data
echo 'rm MPI_TMP/* -rf'
rm MPI_TMP/* -rf

mpirun -np 16 rangular_csfg_mpi > out_rangular_n${n}<<S4
y
S4
du  -h MPI_TMP
ls -lh MPI_TMP/000

# Get initial estimates of wave functions
m=`expr $n - 1`
echo m=$m n=$n
rwfnestimate_csfg > /dev/null 2>&1 <<S5
y
1
n${m}.w
*
3
*
S5

# Perform self-consistent field calculations
mpirun -np 16 rmcdhf_csfg_mpi > out_rmcdhf_n${n}<<S6
y
1-4
1-3
1-3
1-6
1-4
1-3
1-1
5
${n}*

100
S6

## Perform additional RMCDHF calculation to ensure convergence
#mv rwfn.out rwfn.inp
#mpirun -np 16 rmcdhf_csfg_mpi > out_rmcdhf_n${n}<<S6
#y
#1-4
#1-3
#1-3
#1-6
#1-4
#1-3
#1-1
#5
#${n}*
#
#100
#S6

rsave_csfg n${n}

# transform to LSJ-coupling
jj2lsj_csfg > /dev/null 2>&1 <<S1
n${n}
n
y
y
S1

rlevels_csfg n${n}.m > n${n}.lev

   echo)
done

#  Perform Breit-correction using CI for n=9. First copy to other file names

n=9
cp n${n}.g n${n}CI.g
cp n${n}.l n${n}CI.l
cp n${n}.w n${n}CI.w

# rci_csfg_mpi will output automatically nCI${n}.c
mpirun -np 16 rci_csfg_mpi > out_rci_n${n}<<S7
y                  #Default settings?
n${n}CI
y                  #Include contribution of H (Transverse)?
y                  #Modify all transverse photon frequencies?
1.0d-6             #WFACT
n                  #Limit the Breit contributions by n?
15                 #Discard Breit interaction for above n:
n                  #Limit the Breit contributions by l?
14                 #Discard Breit interaction for above l:
y                  #Include H (Vacuum Polarisation, term 2 and 4)?
n                  #Include H (Normal Mass Shift)?
n                  #Include H (Specific Mass Shift)?
y                  #Estimate self-energy?
3                  #NQEDMAX, !!! Largest n quantum number of the sectroscopy orbital !!!!
4                  #MaxMemPerProcs, in GB (INTEGER)
1-4
1-3
1-3
1-6
1-4
1-3
1-1
S7

# transform to LSJ-coupling
jj2lsj_csfg > /dev/null 2>&1 <<S1
n${n}CI
y
y
y
S1

rlevels_csfg n${n}CI.cm > n${n}CI.clev
rm rcsfg.inp rlabel.inp rwfn.out rwfn.inp rcsf.out > /dev/null 2>&1
