!**********************************************************************
!  Written by Chongyang Chen, Fudan university, Shanghai              *
!                                               Nov 2023              *
!**********************************************************************
      MODULE csfg_decide_C
      USE vast_kind_param, ONLY:  DOUBLE

      ! Consider the CI within the diagonal-block generated by ICC-ICC
      ! symmetry-ordered CSF (CSFG)?
      LOGICAL :: LSYMD = .FALSE.

      ! Initianal values are given that these parameters doesn't affect
      ! the behavior original RCI_MPI code.
      ! Discard the Breit contributions invovling very high n orbital?
      LOGICAL :: NDISCARDBR = .FALSE.
      ! Discard the Breit contributions invovling very high l orbital?
      LOGICAL :: LDISCARDBR = .FALSE.
      ! Discard Breit interaction for n above :   
      INTEGER :: NDISBR = 15
      ! Discard Breit interaction for l above :   
      INTEGER :: LDISBR = 14

      ! Change the convergence criterion of eigenvalue?
      ! This option is used to speed up the calculations only for
      ! rmixaccumulate_csfg program.
      LOGICAL :: LCRITE = .FALSE.
      REAL(DOUBLE) :: CRITE0 = 1.0D-12

      ! Maximum size of memory allowed for each MPI process within
      ! diagonalization, input by user
      INTEGER :: MaxMemPerProcs

      END MODULE csfg_decide_C
