      module symmatrix_mod
! CYC 2023/01/11
! Collection all variables 
      use kkstart_C, ONLY : KMAX
      USE parameter_def,   ONLY:  NNNW
      USE vast_kind_param, ONLY:  DOUBLE, LONG
! CYC 2023/01/11

      implicit none
! if symmatrix_mod :: CUTOFF=1.0D-10, the number of non-zero elements 
! counted by rangular_mpi_csfg will be larger than NELMNTCC in
! setham_csfg.
      DOUBLE PRECISION, PARAMETER :: CUTOFF=1.0D-10
      LOGICAL :: LTRANSPOSE  !TRANSPOSE TYPE 5 - 2 TO 2 - 5 
      INTEGER :: IRTOT, ICTOT, MAXSPAN, NORBGEN
      INTEGER :: NODENCOLS
      INTEGER :: LABV(6), IPSym(4), NSYMCR, NSYMCOL, NSYMROW, NSAMESYMCR
!GG      LOGICAL :: LBRPOSEX
      LOGICAL :: LICCUT
      INTEGER, DIMENSION(:),   ALLOCATABLE :: NODECOLS
      INTEGER, DIMENSION(:),   ALLOCATABLE :: MAP
      INTEGER, DIMENSION(:,:), ALLOCATABLE :: NTYPE
      INTEGER, DIMENSION(:,:), ALLOCATABLE :: IROWSYM
      INTEGER, DIMENSION(:),   ALLOCATABLE :: NELCSYM
      DOUBLE PRECISION, DIMENSION(:,:), ALLOCATABLE :: EMTSYM
      DOUBLE PRECISION, DIMENSION(:,:), ALLOCATABLE :: EMTBLOCK
      INTEGER, DIMENSION(:),   ALLOCATABLE :: ICNODES
      INTEGER, DIMENSION(:),   ALLOCATABLE :: NZMCOL

      INTEGER :: ICFICT, IRFICT
      LOGICAL :: LPRINT = .FALSE.
      !LOGICAL :: LPRINT = .TRUE.
      LOGICAL :: LTRANSFER

! CYC 2023/01/11
! Collection all variables 

! libmod/hblock_C.f90
      INTEGER, DIMENSION(20) :: NCFBLKTr
      INTEGER                :: NCFTOTTr

! libmod/kkstart_C.f90
      INTEGER, DIMENSION(0:KMAX*NNNW) :: KSTARTIA

! libmod/kkstartbreit_C.f90
      INTEGER, DIMENSION(0:KMAX*NNNW) :: KSTARTBREIT1IA,KSTARTBREIT2IA

! libmod/decide_C.f90
!      ! Consider the CI within the diagonal-block generated by ICC-ICC
!      ! symmetry-ordered CSF (CSFG)?
!      LOGICAL :: LSYMD = .FALSE.
!      ! Initianal values are given that these parameters doesn't affect
!      ! the behavior original RCI_MPI code.
!      ! Discard the Breit contributions invovling very high n orbital?
!      LOGICAL :: NDISCARDBR = .FALSE.
!      ! Discard the Breit contributions invovling very high l orbital?
!      LOGICAL :: LDISCARDBR = .FALSE.
!      ! Discard Breit interaction for n above :   
!      INTEGER :: NDISBR = 15
!      ! Discard Breit interaction for l above :   
!      INTEGER :: LDISBR = 14
!
!      ! Change the convergence criterion of eigenvalue?
!      ! This option is used to speed up the calculations only for
!      ! rmixaccumulate_sym program.
!      LOGICAL :: LCRITE = .FALSE.
!      REAL(DOUBLE) :: CRITE0 = 1.0D-12

! libmod/where_C.f90
      INTEGER :: IMCDF

! libmod/orb_C.f90
      INTEGER :: NCFTr

! Identify non-zero matrixelements of sub-block between the CSFG pairs.
      LOGICAL, DIMENSION(:,:), ALLOCATABLE :: LNonZero

! Total number of calling ONESCALAR
!      INTEGER(LONG) :: NONESCALAR, NRKCO

      end module symmatrix_mod
