#!/bin/sh
set -x

for n in 4 5 6 7 8 9
do
(cp n${n}.w CIn${n}.w


mpirun -np 20 rci_mpi > out_rci_CIn${n}<<S7
y                  #Default settings?
CIn${n}
y                  #Include contribution of H (Transverse)?
y                  #Modify all transverse photon frequencies?
1.0d-6             #WFACT
y                  #Include H (Vacuum Polarisation, term 2 and 4)?
n                  #Include H (Normal Mass Shift)?
n                  #Include H (Specific Mass Shift)?
y                  #Estimate self-energy?
3                  #NQEDMAX, !!! Largest n quantum number of the sectroscopy orbital !!!!
1-5
1-2
1-3
1-5
1-7
1-5
1-2
1-3
1-2
1
S7
echo

# transform to LSJ-coupling
jj2lsj_2024 > /dev/null 2>&1 <<S1
CIn${n}
y
y
y
S1

rlevels CIn${n}.cm > CIn${n}.clev
   echo)
done
