#!/bin/sh

set -x

rcsfgenerate <<EOF3
*
1
2s(2,*)2p(6,*)3s(2,*)
2s(2,*)2p(6,*)3s(1,*)3d(1,*)
2s(2,*)2p(6,*)3p(2,*)
2s(2,*)2p(6,*)3d(2,*)

9s,9p,9d,9f,9g,9h,9i
0,8
2
y
2s(2,*)2p(6,*)3s(1,*)3p(1,*)
2s(2,*)2p(6,*)3p(1,*)3d(1,*)

9s,9p,9d,9f,9g,9h,9i
0,8
2
n
EOF3

mv rcsf.out CIn.c

# Split into CIn4.c, CIn5.c, CIn6.c, CIn7.c, CIn8.c, CIn9.c, ...

rcsfsplit <<EOF5
CIn
6
4s,4p,4d,4f
4
5s,5p,5d,5f,5g
5
6s,6p,6d,6f,6g,6h
6
7s,7p,7d,7f,7g,7h,7i
7
8s,8p,8d,8f,8g,8h,8i
8
9s,9p,9d,9f,9g,9h,9i
9
EOF5

rm clist.ref clist.new rcsf.out rcsf.log excitationdata > /dev/null 2>&1
