#!/bin/sh
set -x

# 3. For Dirac-Fock calculation

cp n3.c rcsf.inp

mpirun -np 1 rangular_mpi > out_rangular_n3 <<S4
y
S4

#  Get initial estimates of wave functions
rwfnestimate > /dev/null 2>&1 <<S5
y
3
*
S5

# Perform self-consistent field calculations
mpirun -np 1 rmcdhf_mem_mpi > out_rmcdhf_n3 <<S6
y
1-5
1-2
1-3
1-5
1-7
1-5
1-2
1-3
1-2
1
5
*
*
100
S6

# Perform additional RMCDHF calculation to ensure convergence
mv rwfn.out rwfn.inp
mpirun -np 1 rmcdhf_mem_mpi > out_rmcdhf_n3 <<S6
y
1-5
1-2
1-3
1-5
1-7
1-5
1-2
1-3
1-2
1
5
*
*
100
S6

# Save the result to n3
rsave n3

# transform to LSJ-coupling
jj2lsj_2024  > /dev/null 2>&1 <<S1
n3
n
y
y
S1

rlevels n3.m  > n3.lev
rm rcsf.inp rwfn.inp rwfn.out
