#!/bin/sh
set -x

#   4.  Get results for n=4,5,6,7,8,9

for n in 4 5 6 7 8 9
do
   (cp n${n}.c rcsf.inp

#  Get angular data
echo 'rm MPI_TMP/* -rf'
rm MPI_TMP/* -rf

mpirun -np 20 rangular_mpi > out_rangular_n${n}<<S4
y
S4
du  -h MPI_TMP
ls -lh MPI_TMP/000

# Get initial estimates of wave functions
m=`expr $n - 1`
echo m=$m n=$n
rwfnestimate > /dev/null 2>&1 <<S5
y
1
n${m}.w
*
3
*
S5

# Perform self-consistent field calculations
mpirun -np 20 rmcdhf_mem_mpi > out_rmcdhf_n${n}<<S6
y
1-5
1-2
1-3
1-5
1-7
1-5
1-2
1-3
1-2
1
5
${n}*

100
S6

rsave n${n}

# transform to LSJ-coupling
jj2lsj_2024 > /dev/null 2>&1 <<S1
n${n}
n
y
y
S1

rlevels n${n}.m > n${n}.lev

   echo)
done

