      MODULE lodcsh2_csfg_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:49:02   2/14/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE lodcsh2_csfg(NFILE, NCORE, JB)
      INTEGER, INTENT(IN) :: NFILE
      INTEGER, INTENT(OUT) :: NCORE
      INTEGER , INTENT(IN) :: JB
      END SUBROUTINE
      END INTERFACE
      END MODULE
